### ISSUE TITLE
InputField Molecule has duplicate code

### ISSUE THREAD

**Issue by RizaHKhan** [JadRizk/vue3-auth#1]
Hi Jad,

First of all, great repo man, I really learnt alot from it. I was getting into Typescipt in Vue and this repo hit the button.
 
About the above issue, don't you think using a `<slot>` would have been better, specifically for the InputField.molecule file?

I feel that you are duplicating the props (just to pass them again to the input component).

Again, thanks for making this public, its a great learning opportunity.

**Comment by JadRizk** [comment]
Hey Riza,

Thank you for your message. 

I realized that there is something wrong with the way I've implemented the molecule components in this project. I was still new to Vue and didn't have much time to come back to this project. 

If you are interested, you can help me improve this project and maybe turn it into a Vue template for new and advanced developers.

Feel free to submit any modification to the codebase 🚀

Thank you again for your comments and have a wonderful day 💥

**Comment by RizaHKhan** [comment]
With regards to **BaseButton.atom** vs **InputField.molecule** I know it goes against the convention in the application right now, but it might be better to combine them into one component. Labels go with inputs pretty much exclusively and it will prevent alot of the duplicate code in InputFields.molecule.
